// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEz3aA12adszxb31mpZqRAfkVSQaWWILI',
    appId: '1:66529367139:web:3776cfa96a50ae636a9456',
    messagingSenderId: '66529367139',
    projectId: 'flash-chat-a3d89',
    authDomain: 'flash-chat-a3d89.firebaseapp.com',
    storageBucket: 'flash-chat-a3d89.appspot.com',
    measurementId: 'G-5SDN9QY8GD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDLBK34D6ECj3X3qhmaztpK32UeR8_Ktw',
    appId: '1:66529367139:android:a47e49bc057b5c666a9456',
    messagingSenderId: '66529367139',
    projectId: 'flash-chat-a3d89',
    storageBucket: 'flash-chat-a3d89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPQZn9j2-WP089dVaM3s7Rzfoqc0bvMRs',
    appId: '1:66529367139:ios:a94f16bc0e7e62b96a9456',
    messagingSenderId: '66529367139',
    projectId: 'flash-chat-a3d89',
    storageBucket: 'flash-chat-a3d89.appspot.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPQZn9j2-WP089dVaM3s7Rzfoqc0bvMRs',
    appId: '1:66529367139:ios:73f5205aa50b387e6a9456',
    messagingSenderId: '66529367139',
    projectId: 'flash-chat-a3d89',
    storageBucket: 'flash-chat-a3d89.appspot.com',
    iosBundleId: 'com.example.flashChat.RunnerTests',
  );
}
